Improved ListSelector control.
SafeTwice/XtraControls pull request #1
Opened 2024-10-29 17:23 UTC by JsanchezCynoss

Improved ListSelector control, with options to change Available/Selected header names.

2024-10-31 11:56 UTC, jgonzalez-stw requested changes

2024-10-31 11:56 UTC, jgonzalez-stw commented on Lib/ListSelector/ListSelector.xaml.cs
> +            ( (ListSelector) d ).OnAvailableItemsSourcePropertyChangedEvent( (IEnumerable) e.OldValue, (IEnumerable?) e.NewValue );
Good point in taking in account that e.NewValue may be null, but this should be also be considered for e.OldValue.

In fact, just handling nulls in the called function should be enough, maybe the (IEnumerable?) cast here is unnecessary.

2024-11-06 10:54 UTC, JsanchezCynoss commented on Lib/ListSelector/ListSelector.xaml.cs
> +            ( (ListSelector) d ).OnAvailableItemsSourcePropertyChangedEvent( (IEnumerable) e.OldValue, (IEnumerable?) e.NewValue );
Unnecessary cast has been removed and handled only in the call, also for OldValue.

2024-11-20 09:37 UTC, jgonzalez-stw approved these changes

2024-11-20 09:37 UTC, jgonzalez-stw approved these changes

2024-11-20 09:38 UTC, jgonzalez-stw approved these changes
OK

2024-11-20 09:39 UTC, merged